# Generated by Django 5.1.4 on 2026-06-09 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(db_index=True, max_length=200)),
                ("contacto", models.CharField(blank=True, max_length=200)),
                ("tel", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("dir", models.CharField(blank=True, max_length=300)),
                ("rfc", models.CharField(blank=True, max_length=20)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("publico", "Publico"), ("mayoreo", "Mayoreo")],
                        db_index=True,
                        default="publico",
                        max_length=20,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                ("activo", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "customers_customer",
                "ordering": ["nombre"],
                "indexes": [
                    models.Index(
                        fields=["tipo", "activo"], name="customers_c_tipo_8a5a8f_idx"
                    ),
                    models.Index(
                        fields=["nombre"], name="customers_c_nombre_28819b_idx"
                    ),
                ],
            },
        ),
    ]
