# Generated by Django 5.1.4 on 2026-06-09 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=40, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("desc", models.TextField(blank=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("block", "Block"),
                            ("cemento", "Cemento y Cal"),
                            ("acero", "Acero"),
                            ("agregados", "Agregados"),
                            ("prefabricados", "Prefabricados"),
                            ("otros", "Otros"),
                        ],
                        db_index=True,
                        default="otros",
                        max_length=30,
                    ),
                ),
                (
                    "unidad",
                    models.CharField(
                        choices=[
                            ("pieza", "Pieza"),
                            ("saco", "Saco"),
                            ("m3", "Metro cubico"),
                            ("kg", "Kilogramo"),
                            ("hoja", "Hoja"),
                            ("millar", "Millar"),
                            ("m2", "Metro cuadrado"),
                            ("cubeta", "Cubeta"),
                        ],
                        default="pieza",
                        max_length=20,
                    ),
                ),
                ("precio", models.DecimalField(decimal_places=2, max_digits=12)),
                ("mayoreo", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "costo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("stock", models.IntegerField(default=0)),
                ("stock_min", models.IntegerField(default=0)),
                ("activo", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "db_table": "products_product",
                "ordering": ["categoria", "nombre"],
                "indexes": [
                    models.Index(
                        fields=["activo", "categoria"],
                        name="products_pr_activo_f9ad8d_idx",
                    ),
                    models.Index(
                        fields=["stock", "stock_min"],
                        name="products_pr_stock_5b0cb6_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("precio__gte", 0)), name="precio_gte_0"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("stock__gte", 0)), name="stock_gte_0"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InventoryMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("salida", "Salida"),
                            ("ajuste", "Ajuste"),
                            ("venta", "Venta"),
                        ],
                        max_length=20,
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("stock_after", models.IntegerField()),
                ("nota", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inventory_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "db_table": "products_movement",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-created_at"],
                        name="products_mo_product_744274_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="products_mo_created_d9267e_idx"
                    ),
                ],
            },
        ),
    ]
