# Generated by Django 5.1.4 on 2026-06-09 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("folio", models.CharField(db_index=True, max_length=20, unique=True)),
                ("fecha", models.DateField(db_index=True)),
                ("hora", models.TimeField()),
                (
                    "metodo",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("transferencia", "Transferencia"),
                            ("tarjeta", "Tarjeta"),
                            ("credito", "Credito"),
                        ],
                        default="efectivo",
                        max_length=20,
                    ),
                ),
                ("aplica_iva", models.BooleanField(default=False)),
                (
                    "descuento_pct",
                    models.DecimalField(decimal_places=4, default=0, max_digits=5),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "descuento_monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "iva_monto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("notas", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sales",
                        to="customers.customer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "db_table": "sales_sale",
                "ordering": ["-fecha", "-hora"],
            },
        ),
        migrations.CreateModel(
            name="SaleItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("importe", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sale_items",
                        to="products.product",
                    ),
                ),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.sale",
                    ),
                ),
            ],
            options={
                "db_table": "sales_saleitem",
            },
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["-fecha", "-hora"], name="sales_sale_fecha_1b7fda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["customer", "-fecha"], name="sales_sale_custome_0efc22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sale",
            index=models.Index(
                fields=["user", "-fecha"], name="sales_sale_user_id_312649_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="saleitem",
            index=models.Index(fields=["sale"], name="sales_salei_sale_id_413ea3_idx"),
        ),
        migrations.AddIndex(
            model_name="saleitem",
            index=models.Index(
                fields=["product"], name="sales_salei_product_f87493_idx"
            ),
        ),
    ]
